name: sciedu-dev

services:
  backend:
    image: nycusdc/sciedu-backend:dev
    networks:
      - internal
      - traefik
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ENV=dev
      - HOST=0.0.0.0
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - NYCU_OAUTH_CLIENT_ID=${NYCU_OAUTH_CLIENT_ID}
      - NYCU_OAUTH_CLIENT_SECRET=${NYCU_OAUTH_CLIENT_SECRET}
      - SECRET=${SECRET}
      - SLURM_TOKEN_HELPER_URL=${SLURM_TOKEN_HELPER_URL}
      - SLURM_RESTFUL_BASE_URL=${SLURM_RESTFUL_BASE_URL}
    labels:
      - "vector.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.sciedu-backend-dev.rule=Host(`api.dev.sciedu.sdc.nycu.club`)"
      - "traefik.http.routers.sciedu-backend-dev.entrypoints=websecure"
      - "traefik.http.routers.sciedu-backend-dev.tls=true"
      - "traefik.http.routers.sciedu-backend-dev.tls.certresolver=cloudflare"
      - "traefik.http.services.sciedu-backend-dev.loadbalancer.server.port=8080"


  postgres:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sciedu
    networks:
      - internal


networks:
  internal:
  traefik:
    external: true