name: sciedu-$VERSION

services:
  backend:
    image: "ghcr.io/nycu-sdc/sciedu-backend:$VERSION"
    networks:
      - internal
      - traefik
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DEV=true
      - ENV=snapshot
      - HOST=0.0.0.0
      - BASE_URL=https://api.dev.sciedu.sdc.nycu.club
      - DATABASE_URL=postgres://postgres:password@postgres:5432/sciedu?sslmode=disable
      - MIGRATION_SOURCE=file://app/migrations
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sciedu-backend-${VERSION}.rule=Host(`api.${VERSION}.sciedu.sdc.nycu.club`)"
      - "traefik.http.routers.sciedu-backend-${VERSION}.entrypoints=websecure"
      - "traefik.http.routers.sciedu-backend-${VERSION}.tls=true"
      - "traefik.http.routers.sciedu-backend-${VERSION}.tls.certresolver=cloudflare"
      - "traefik.http.services.sciedu-backend-${VERSION}.loadbalancer.server.port=8080"
      - "vector.enable=true"

  postgres:
    image: postgres:18.1
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sciedu
    networks:
      - internal

networks:
  internal:
  traefik:
    external: true