name: sciedu-$VERSION

services:
  backend:
    image: "nycusdc/sciedu-backend:$VERSION"
    networks:
      - internal
      - traefik
    depends_on:
      postgres:
        condition: service_healthy
      ldap:
        condition: service_healthy
    environment:
      - ENV=snapshot
      - HOST=0.0.0.0
      - BASE_URL=https://api.$VERSION.sciedu.sdc.nycu.club
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - NYCU_OAUTH_CLIENT_ID=${NYCU_OAUTH_CLIENT_ID}
      - NYCU_OAUTH_CLIENT_SECRET=${NYCU_OAUTH_CLIENT_SECRET}
      - SECRET=${SECRET}
      - OAUTH_PROXY_BASE_URL=https://oauth-proxy.eng.sdc.nycu.club
      - OAUTH_PROXY_SECRET=${OAUTH_PROXY_SECRET}
      - DATABASE_URL=postgres://postgres:password@postgres:5432/sciedu?sslmode=disable
      - BASE_URL=https://api.$VERSION.sciedu.sdc.nycu.club
      - SLURM_TOKEN_HELPER_URL=${SLURM_TOKEN_HELPER_URL}
      - SLURM_RESTFUL_BASE_URL=${SLURM_RESTFUL_BASE_URL}
      - SLURM_RESTFUL_VERSION=v0.0.43
      - MIGRATION_SOURCE=file:///app/migrations
      - CASBIN_POLICY_SOURCE=policy.csv
      - CASBIN_MODEL_SOURCE=model.conf
      - ALLOW_ORIGINS=*
      - OTEL_COLLECTOR_URL=10.140.0.3:4317
      - PRESET_USER=Wwp7InVzZXIiOiJreWxlOTQxMDEwQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiJ9LAp7InVzZXIiOiJiZW5kb3JpczA1MDlAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIn0sCnsidXNlciI6ICJoMjM3azc3Nzc3QGdtYWlsLmNvbSIsICJyb2xlIjoiYWRtaW4ifSwKeyJ1c2VyIjogImFubmllMTA3MzEzMDNAZ21haWwuY29tIiwgInJvbGUiOiJhZG1pbiJ9LAp7InVzZXIiOiAiMXA0MXA0amVqb0BnbWFpbC5jb20iLCAicm9sZSI6ImFkbWluIn0sCnsidXNlciI6ICJueWFuMjIyNzI3QGdtYWlsLmNvbSIsICJyb2xlIjoiYWRtaW4ifSwKeyJ1c2VyIjogImFuMTEyNTUwMDA3LmNzMTJAbnljdS5lZHUudHciLCAicm9sZSI6ImFkbWluIn0sCnsidXNlciI6ICJrb3Jlbi5saW5AZ2FwcC5udGh1LmVkdS50dyIsICJyb2xlIjoiYWRtaW4ifQpd
    labels:
      - "vector.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.sciedu-backend-$VERSION.rule=Host(`api.$VERSION.sciedu.sdc.nycu.club`)"
      - "traefik.http.routers.sciedu-backend-$VERSION.entrypoints=websecure"
      - "traefik.http.routers.sciedu-backend-$VERSION.tls=true"
      - "traefik.http.routers.sciedu-backend-$VERSION.tls.certresolver=cloudflare"
      - "traefik.http.services.sciedu-backend-$VERSION.loadbalancer.server.port=8080"


  postgres:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sciedu
    networks:
      - internal



networks:
  internal:
  traefik:
    external: true