name: sciedu-stage

services:
  backend:
    image: "ghcr.io/nycu-sdc/sciedu-backend:stage"
    networks:
      - internal
      - traefik
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ENV=stage
      - HOST=0.0.0.0
      - BASE_URL=https://api.dev.sciedu.sdc.nycu.club
      - DATABASE_URL=postgres://postgres:password@postgres:5432/sciedu?sslmode=disable
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sciedu-backend-stage.rule=Host(`api.stage.sciedu.sdc.nycu.club`)"
      - "traefik.http.routers.sciedu-backend-stage.entrypoints=websecure"
      - "traefik.http.routers.sciedu-backend-stage.tls=true"
      - "traefik.http.routers.sciedu-backend-stage.tls.certresolver=cloudflare"
      - "traefik.http.services.sciedu-backend-stage.loadbalancer.server.port=8080"

  postgres:
    image: postgres:18.1
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sciedu
    networks:
      - internal


networks:
  internal:
  traefik:
    external: true